### ISSUE TITLE
My Flutter version 2.2.2

### ISSUE THREAD

**Issue by DineshJat123** [newtaDev/pod_player#10]
I Have problem how to solve the

**Comment by newtaDev** [comment]
Please mention your problem

**Comment by DineshJat123** [comment]
my  environment:
  sdk: ">=2.10.4 <3.0.0"
and flutter version 2.2.2
my project is big thus i am not able to upgrate flutter i want to use this player How can use this player

**Comment by newtaDev** [comment]
can u please mention what's the error or issue  u got while using this package in `flutter -v 2.2.2`

**Comment by DineshJat123** [comment]
version: 1.0.1+1

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
pod_player:

[idemy] flutter pub get
Running "flutter pub get" in idemy...                           
The current Dart SDK version is 2.13.3.



Because student_app depends on pod_player any which requires SDK version >=2.16.1 <3.0.0, version solving failed.
pub get failed (1; Because student_app depends on pod_player any which requires SDK version >=2.16.1 <3.0.0, version solving failed.)
exit code 1

**Comment by newtaDev** [comment]
Update your dart sdk version

``` brew upgrade dart ```

> environment:
 sdk: ">=2.10.4 <3.0.0"

To 

> environment:
sdk: ">=2.16.1 <3.0.0"
