### ISSUE TITLE
Try correcting the name to the name of an existing getter, or defining a getter or field named 'qualityLabel'

### ISSUE THREAD

**Issue by theappideasankit** [newtaDev/pod_player#107]
Performing hot restart...
Syncing files to device iPhone SE (3rd generation)...
../../../.pub-cache/hosted/pub.dartlang.org/pod_player-0.0.6/lib/src/utils/video_apis.dart:55:42: Error: The getter 'qualityLabel' isn't defined for the class 'MuxedStreamInfo'.
 - 'MuxedStreamInfo' is from 'package:youtube_explode_dart/src/videos/streams/muxed_stream_info.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/youtube_explode_dart-1.9.10/lib/src/videos/streams/muxed_stream_info.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'qualityLabel'.
              quality: int.parse(element.qualityLabel.split('p')[0]),
                                         ^^^^^^^^^^^^
<img width="1003" alt="Screenshot 2023-05-08 at 9 50 16 AM" src="https://user-images.githubusercontent.com/97028121/236733054-66f9b3ec-4d17-4698-90de-d94ac74d9b27.png">

**Comment by newtaDev** [comment]
Try cleaning the pub cache

**Comment by theappideasankit** [comment]
not working

> Try cleaning the pub cache

**Comment by theappideasankit** [comment]
solved 

 final _urls = muxed
          .map(
            (element) => VideoQalityUrls(
              quality: int.parse(element.videoQualityLabel.split('p')[0]),
              url: element.url.toString(),
            ),
          )
          .toList();

click this error file Video_apis.dart and edit this line
