### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by rakib205** [newtaDev/pod_player#115]
Hi there, I am facing this error on the pod player latest version. I tried an older version as well but the error is still the same. I am using flutter latest version 3.10.1.

../../../../../../.pub-cache/hosted/pub.dev/universal_html-2.2.2/lib/src/html/dom/element_subclasses.dart:2752:30: Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
    final parsed = css.parse(text);
                             ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/rakibbhuiyan/tools/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1201

**Comment by abdorizak** [comment]
Hi @rakib205 i was facing this issue for the same before hour ago this something related for this package other dependency are need to upgrade maybe the owner doesn't figure out the outdated version for this package dependencies

**Comment by rakib205** [comment]
@newtaDev, Can you please look at it?

**Comment by abdorizak** [comment]
@newtaDev let me try to resolve i'll take this issue thanks

**Comment by rakib205** [comment]
@newtaDev
