### ISSUE TITLE
How to use full screen

### ISSUE THREAD

**Issue by DineshJat123** [newtaDev/pod_player#12]
this player has margin around i want to use full screen this please solve tis problems

**Comment by newtaDev** [comment]
by default in fullscreen view, it doesn't have any margin..

Can u share a screenshot

**Comment by gtu-myowin** [comment]
@newtaDev Why not just [push to root context](https://stackoverflow.com/a/60372154/2218290)?

If you push full screen into root context everything of the app will be sent back. Here is the example code

```dart
onPressed: () {
        Navigator.of(context, rootNavigator: true).push(
          CupertinoPageRoute<bool>(
            fullscreenDialog: true,
            builder: (BuildContext context) => Tab3Dialog(),
          ),
        );
      },
```

In the mean time how can I use this with your package?
