### ISSUE TITLE
Seek not working on videos

### ISSUE THREAD

**Issue by flutternoob** [newtaDev/pod_player#13]
Hi. I updated the library to the latest version for the autoplay feature. However, after the update, video seek does not work if the ```PodPlayerConfig``` class is instantiated as a ```const```.

In the following code, video seek does not work:

```
podPlayerConfig: const PodPlayerConfig(
        autoPlay: false,
        isLooping: false
      )
```

In the following code, video seek works:

```
podPlayerConfig: PodPlayerConfig(
        autoPlay: false,
        isLooping: false
      )
```

**Comment by newtaDev** [comment]
works perfectly for me

can u record your screen and share, if this issue still exists

**Comment by flutternoob** [comment]
Its working now. I had to do a hot restart because the controller's initialisation is in ```initState()```. Sorry for the mix up. Closing the issue. Thanks
