### ISSUE TITLE
http dependency update required

### ISSUE THREAD

**Issue by rakib205** [newtaDev/pod_player#131]
Because pod_player 0.2.0 depends on http ^0.13.6 and no versions of pod_player match >0.2.0 <0.3.0, pod_player ^0.2.0 requires http ^0.13.6.

Can't use http: ^1.1.0

**Comment by alhazmy13** [comment]
same issue

**Comment by Merculiar** [comment]
Same issue, please fix

**Comment by newtaDev** [comment]
Upgraded dependencis in `pod_player 0.2.1`
