### ISSUE TITLE
Unable to Find assets folder

### ISSUE THREAD

**Issue by razer-santhosh** [newtaDev/pod_player#136]
Error: unable to find directory entry in pubspec.yaml: C:\Users\SSG\AppData\Local\Pub\Cache\hosted\pub.dev\pod_player-0.1.2\assets\

Whenever, I use cache clean, I have to manually create this empty folder to solve this

**Comment by newtaDev** [comment]
Had some issues with `0.1.2` version 
Upgrade pod_player to >=`0.2.1`

I'm closing the issue,
if you are still facing same issue please feel free to reopen
