### ISSUE TITLE
Bottom navigation bar visible on full screen

### ISSUE THREAD

**Issue by Abi2737** [newtaDev/pod_player#14]
Hi,

Is there anything you can do to hide the bottom navigation bar on full screen? 
![Screenshot_20220423-115035](https://user-images.githubusercontent.com/23168370/164887778-4c8a3174-c887-40af-82e2-5306afb13a84.jpg)

**Comment by newtaDev** [comment]
No, pod_player cannot hide your bottomNavBar

but you can toggle it by, just checking if the video Player is in fullScreen or not

**Comment by gtu-myowin** [comment]
@newtaDev Why not just [push to root context](https://stackoverflow.com/a/60372154/2218290)?

If you push full screen into root context everything of the app will be sent back. Here is the example code

```dart
onPressed: () {
        Navigator.of(context, rootNavigator: true).push(
          CupertinoPageRoute<bool>(
            fullscreenDialog: true,
            builder: (BuildContext context) => Tab3Dialog(),
          ),
        );
      },
```

In the mean time how can I use this with your package?
