### ISSUE TITLE
youtube live supported for latest version?

### ISSUE THREAD

**Issue by wilson0506** [newtaDev/pod_player#150]
===== YOUTUBE API ERROR: Invalid argument (urlOrUrl): Invalid YouTube video ID or URL: "https://www.youtube.com/live/XXXXXXXX" 

can it be auto detected  with setting ,live: true

**Comment by wilson0506** [comment]
also fail for this format of live video, 
https://www.youtube.com/watch?v=XXXXXXXX

**Comment by newtaDev** [comment]
Yes you can set `live = true` to play live videos

**Comment by wilson0506** [comment]
but can it be, if there is live, then use live:true, if the live is finished, then use live:false automatically?
