### ISSUE TITLE
Playing youtube videos on iOS/Android not working

### ISSUE THREAD

**Issue by reliance-engineer** [newtaDev/pod_player#153]
On iOS I got this error:

```
PlatformException(VideoError, Failed to load video: unknown error, null, null)
```

on Android:
```
PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
```

my code:
```
@override
  void onInit() {
    repository = CityRepository();
    playerController = PodPlayerController(
      playVideoFrom:
          PlayVideoFrom.youtube(YoutubePlayer.convertUrlToId('https://youtu.be/gsnqXt7d1mU')!),
      podPlayerConfig: const PodPlayerConfig(
        autoPlay: false,
        isLooping: false,
        forcedVideoFocus: false,
        wakelockEnabled: true,
      ),
    )..initialise();
    playerController.addListener(onVideoStateChanged);
    change(null, status: RxStatus.loading());
    super.onInit();
  }
```

the error is thrown in `pod_getx_video_controller.dart` line 78

**Comment by Masum-MSNR** [comment]
same problem

**Comment by Masum-MSNR** [comment]
@reliance-engineer did you manage to solve the problem?

**Comment by Nguyenducthien98ha** [comment]
I also got the same error

**Comment by newtaDev** [comment]
Will have a look ASAP

**Comment by mahmoud98alali** [comment]
I have same the problem

**Comment by 4dcity** [comment]
same problem
anyone solve the problem?

**Comment by newtaDev** [comment]
I have checked the video URL you provided (https://youtu.be/gsnqXt7d1mU) with the `example app`  from this repo its working fine for me,
check here:
https://github.com/newtaDev/pod_player/blob/master/example/lib/screens/from_youtube.dart

to run example app:

clone pod_player repo and run the example app from `./example` folder

**Comment by newtaDev** [comment]
if the issue still exists please share reproducible code here

**Comment by Nguyenducthien98ha** [comment]
I have updated to the latest version and it works fine

**Comment by reliance-engineer** [comment]
Yes, I also update to the latest version and it works now, I was 2 versions behind
