### ISSUE TITLE
List of controllers to be used in a ListView.builder

### ISSUE THREAD

**Issue by inc16sec** [newtaDev/pod_player#18]
Is there a way to add a list of video controllers to be used in a `listView.builder`.

Let's say I have a list of videos and I want to initialize the video before it shows on the screen (so it won't be loading when on-screen) but also not to dispose of the controller when I scroll up. The ideal approach would be to have a list of controllers (let's say 4 or 5 controllers) and you initialize one controller or more when needed and you don't dispose of the used controllers until a 6th video is close to the screen, so you dispose of the 1st controller (but you still have 2,3,4,5 and 6th video controller) this way even when you scroll down a little bit the controller is still there and when you scroll back up the video plays immediately without loading.

An example of this can be seen [here](https://github.com/jhomlala/betterplayer/tree/master/example/lib/pages/reusable_video_list) but the issue with this approach (or the player itself) is that it is not smooth when initializing. It stutters a bit, which is not cool when you have a list (which is already barely smooth with all the custom widgets).

Thank you so much and let me know if it is possible.
Best regards.

**Comment by newtaDev** [comment]
Yeah it is posible to do,
i will create a example app with these requirements and will share ASAP🤗

**Comment by newtaDev** [comment]
use > `pod_player: ^0.0.6`

Ref [Example](https://github.com/newtaDev/pod_player/blob/master/example/lib/examples/play_list_of_videos.dart)

**Comment by inc16sec** [comment]
> use > `pod_player: ^0.0.6`
> 
> Ref [Example](https://github.com/newtaDev/pod_player/blob/master/example/lib/examples/play_list_of_videos.dart)

This sounds to do it. Thank you so much for your work I highly appreciate it. I'll do more testing with the example now and hopefully, it gets to work in a different scenario too.
