### ISSUE TITLE
 VIMEO API ERROR

### ISSUE THREAD

**Issue by tejaschinni** [newtaDev/pod_player#184]
Unable to play video from vimeo getting error 
 VIMEO API ERROR: type 'Null' is not a subtype of type 'List<dynamic>' in type cast

**Comment by newtaDev** [comment]
This error is thrown because, Vimeo changed their API response, So our implementation is breaking, 
Let me try to find a fix for this issue ASAP

**Comment by newtaDev** [comment]
Im closing this issue, because its a dupe of #182 182
