### ISSUE TITLE
after upgrading to v0.2.2 sound is not coming in the video

### ISSUE THREAD

**Issue by HasithaAcc** [newtaDev/pod_player#188]
after I got the issue in vimeo API error and I saw the fix and updated. Now I don't hear the sound of the video

this issue is coming when we use vimeo id and the hash

**Comment by JAYTARPARA** [comment]
Same issue I am facing

**Comment by JAYTARPARA** [comment]
I did temporary fix by my self by updating from url: '$firstUrlPiece/sep/video/$urlId/$lastUrlPiece', to url: cdnVideoUrl, in \lib\src\utils\video_apis.dart file (This is core file of package not your project file)

**Comment by JAYTARPARA** [comment]
@HasithaAcc

**Comment by HasithaAcc** [comment]
> I did temporary fix by my self by updating from url: '$firstUrlPiece/sep/video/$urlId/$lastUrlPiece', to url: cdnVideoUrl, in \lib\src\utils\video_apis.dart file (This is core file of package not your project file)

Thanks a lot. Let me give a try

this worked for me as well @JAYTARPARA 
appreciate your help
Thanks again

**Comment by bright2kwame** [comment]
Thanks @JAYTARPARA 

For anyone still struggling as atemporal fix: clone the project and make the change recommended by @JAYTARPARA and then add the project to your project root level and then add it to your dependencies. Example below 

dependencies:

  flutter:
    sdk: flutter
 
  pod_player:
    path: pod_player

<img width="741" alt="image" src="https://github.com/newtaDev/pod_player/assets/7769603/3d2b0815-5e9c-4e5a-8e72-0f9cd3b07a37">

**Comment by HasithaAcc** [comment]
Thanks to @JAYTARPARA above solution works really well. so closing this issue

**Comment by falt008** [comment]
> I did temporary fix by my self by updating from url: '$firstUrlPiece/sep/video/$urlId/$lastUrlPiece', to url: cdnVideoUrl, in \lib\src\utils\video_apis.dart file (This is core file of package not your project file)

@newtaDev Do you plan to integrate this change/fix into master? I have the same issue and the fix works for me aswell but I dont really want to have a seperate/custom version of this package. The suggestion in https://github.com/newtaDev/pod_player/issues/195 does not work for me.

**Comment by mateusfmfm** [comment]
Hello guys, I cloned the repo and make the changes locally, what I'm doing wrong?

 '$firstUrlPiece/sep/video/$urlId/$lastUrlPiece', to url: cdnVideoUrl,

From:

<img width="511" alt="image" src="https://github.com/newtaDev/pod_player/assets/44587544/6ea08ec2-ee7e-43a7-8b5c-e238b530168f">

To:

<img width="525" alt="image" src="https://github.com/newtaDev/pod_player/assets/44587544/532aa404-6aac-4448-a2cd-996a79c19e8c">

**Comment by ahmmosaad** [comment]
great job bro @JAYTARPARA
