### ISSUE TITLE
Error Playing Vimeo Video with Id and Hashed

### ISSUE THREAD

**Issue by bright2kwame** [newtaDev/pod_player#189]
===== VIMEO API ERROR: type 'Null' is not a subtype of type 'List<dynamic>' in type cast ==========

**Comment by bright2kwame** [comment]
Unhandled Exception: type 'Null' is not a subtype of type 'List<dynamic>' in type cast

**Comment by robertjones26** [comment]
I cam across this and had to add the header with token. I searched for a couple of days and I think something changed on Vimeos side.

 header = {
    'Authorization': 'bearer {token}',
    'Accept': 'application/vnd.vimeo.*+json;version=3.4',
  };

**Comment by bright2kwame** [comment]
Thank you @robertjones26 I solved it by upgrading to the latest package release
