### ISSUE TITLE
[Futter 3.0] 

### ISSUE THREAD

**Issue by deniealusa** [newtaDev/pod_player#21]
flutter 3.0 upgrade version
Pod_player 0.0.5 
I upgraded two software and encountered the following error.
Are the others okay?
![flutter](https://user-images.githubusercontent.com/68718939/169173008-e2b034c4-fd0a-4365-b06e-d6267f67f90b.png)

**Comment by deniealusa** [comment]
Thank you for your support.

**Comment by newtaDev** [comment]
[Upgraded](https://github.com/newtaDev/pod_player/commit/4652a1da07bd5a7afd43ec669721f14fba4de49f) to `Dart 2.17.0`
