### ISSUE TITLE
Exeception : videoQuality cannot be empty (vimeo private videos)

### ISSUE THREAD

**Issue by UrvishShaligram** [newtaDev/pod_player#226]
Here is my podplayercontroller for playing vimeo private videos :
  
  late final controller = PodPlayerController(
    playVideoFrom: PlayVideoFrom.vimeoPrivateVideos("393556569",
        httpHeaders:{'Authorization': 'Bearer $token'}),
    podPlayerConfig: const PodPlayerConfig(
      isLooping: true,videoQualityPriority: [1080, 720, 360]),
  );
  
 when I checkout the library code, the vimeoVideoUrls is empty and its coming from API , there is no parameter with the matching key written in library code, so library needs to update the code. 
 
 Anyone have any solution to solve  this issue?

![image](https://github.com/user-attachments/assets/8e232ef9-a14b-4741-ad5a-002996c6f75d)

![image](https://github.com/user-attachments/assets/20e28e68-cb70-4e32-9e9b-1f88ad109422)

![image](https://github.com/user-attachments/assets/7c6ad906-b017-45be-af5d-12fbfcdc5336)

**Comment by UllashPodder** [comment]
I have played private videos using pod player for a client's project. I believe Vimeo's documentation is not detailed enough, this only works with Vimeo account with **Pro account subscription**. Free or starter accounts doesn't work. While creating the Vimeo app check private and video files

<img width="658" alt="image" src="https://github.com/user-attachments/assets/a517c761-ef6c-4e6d-92a3-3289ccdb444a">

**Comment by jeremywsimpson44** [comment]
Here is the solution of this error, 
You just have to Generate New Personal Access Tokens with given Scopes in the Screenshot.
Note : Do not forget to copy the new access token.

![image](https://github.com/user-attachments/assets/d46befca-7d08-4e1d-b669-d4db42c0131f)

Also, Initialize your PodPlayerController using below code in your app ,

  String accessToken = 'YOURACCESSTOKEN';

  late final controller = PodPlayerController(
    playVideoFrom: PlayVideoFrom.vimeoPrivateVideos(widget.video.url,
        httpHeaders:{'Authorization': 'Bearer $accessToken'}),
    podPlayerConfig: const PodPlayerConfig(autoPlay: false),
  );

Your vimeo private video will be played successfully.

**Comment by yashgandhishaligram** [comment]
Here is the solution of this error, 
You just have to Generate New Personal Access Tokens with given Scopes in the Screenshot.
Reference Link : https://help.vimeo.com/hc/en-us/articles/12427789081745-How-do-I-generate-a-personal-access-token
Note : Do not forget to copy the new access token.

![accestoken](https://github.com/user-attachments/assets/0a068261-8235-452f-acc4-fa4740b219aa)

Also, Initialize your PodPlayerController using below code in your app 

  String accessToken = 'YOURACCESSTOKEN';

  late final controller = PodPlayerController(
    playVideoFrom: PlayVideoFrom.vimeoPrivateVideos(widget.video.url,
        httpHeaders:{'Authorization': 'Bearer $accessToken'}),
    podPlayerConfig: const PodPlayerConfig(autoPlay: false),
  );

Your vimeo private video will be played successfully.
