### ISSUE TITLE
Youtube Videos load after taking significant time.

### ISSUE THREAD

**Issue by prashantspandey** [newtaDev/pod_player#23]
We are using pod player to play youtube video. Everything is perfect. But the only problem is that the videos are taking a significant amount of time to load and start playing.
This is making the plugin unsable, otherwise this is an awesome plugin. 
Keep up the good work.

**Comment by newtaDev** [comment]
Okay,
Now this issue is being reported frequently (#9, #20, #22 )
Let me see if I can find any workaround for this problem

**Comment by prashantspandey** [comment]
Please can you update me on the estimated time it will take?

Thanks

**Comment by newtaDev** [comment]
> Please can you update me on the estimated time it will take?
> 
> Thanks

https://github.com/newtaDev/pod_player/issues/9#issuecomment-1133885987
