### ISSUE TITLE
Unhandled Exception: Exception: videoQuality cannot be empty

### ISSUE THREAD

**Issue by shayar-ghafour** [newtaDev/pod_player#237]
I am getting this error since yesterday.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: videoQuality cannot be empty
#0      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:73:9)
#1      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:82:11)
<asynchronous suspension>
#2      PodPlayerController.initialise (package:pod_player/src/controllers/pod_player_controller.dart:61:5)
<asynchronous suspension>
```

Flutter 3.22.3
Dart 3.4.4
pod_player: ^0.2.2
youtube_explode_dart: ^2.2.3
affected os both iOS and Android

**Comment by alfayedoficial** [comment]
I am currently experiencing an issue. Is anyone else facing the same problem or found a solution?

**Comment by ceellyy9711** [comment]
I also have this problem..

**Comment by jelle-limpens** [comment]
Same problem here

**Comment by jelle-limpens** [comment]
In youtube_explode_dart 2.2.2 it stopped working returning video's, probably YouTube changing something in their API. In the new version, youtube explode for some reason can't return "muxed" videos, therefore there are only video only and audio only links, and thus pod player not working.

**Comment by TanvirMahin24** [comment]
Same issue here :(

**Comment by jelle-limpens** [comment]
Confirmed from youtube explode that the muxed videos are not avaible through youtubes api with the current stream client; this may or may not be fixed with youtube explode depending on a working stream client.

Pod player itself can change their player to handle youtube videos differently, with iframe example.

Currently there are 2 possible solutions:

1. Continue to use youtube explode and retrieve the video_only and audio_only files, combine them with FFMPEG and display them using a videoplayer (you can alter pod_player to play local video's)
2. Use https://pub.dev/packages/youtube_player_flutter, very easy to implement and works okay

**Comment by balakrishdq** [comment]
Any solutions

**Comment by jelle-limpens** [comment]
> Any solutions

Yes, actually I provided 2 above...

**Comment by balakrishdq** [comment]
May i know what is muxed videos?

**Comment by jelle-limpens** [comment]
> May i know what is muxed videos?

Muxed videos are complete videos, with audio and video combined.

**Comment by mkamel44** [comment]
the same error
![Screenshot_2](https://github.com/user-attachments/assets/16bc8b2f-ca7c-4f9c-bd9b-c915b42d9e1d)

**Comment by Purehi** [comment]
**Changed this. It's working for me.**

`Stream<StreamInfo> _getStreams(VideoId videoId, {required bool fullManifest}) async* {
    try {
 
      if (fullManifest) {
        await for (final stream
            in _getStream(videoId, VideoController.androidClient)) {
          yield stream;
        }
      }else{
        // Use await for instead of yield* to catch exceptions
        await for (final stream
        in _getStream(videoId, VideoController.iosClient)) {
          yield stream;
        }
      }
    } on VideoUnplayableException catch (e) {
      if (e is VideoRequiresPurchaseException) {
        rethrow;
      }
      yield* _getCipherStream(videoId);
    }
  }
`

**How to use**
final manifest = await yt.videos.streamsClient.getManifest(youtubeIdOrUrl, fullManifest: true);

I have updated my app, you can check it out.
[WeTube:Video&Music](https://play.google.com/store/apps/details?id=free.mor.mordo.do)

**Comment by pdechanoz** [comment]
For me it's work after:

flutter clean
flutter pub cache clean
flutter pub get

**Comment by pdechanoz** [comment]
And :
flutter pub outdated
flutter pub upgrade

**Comment by rymesaint** [comment]
i'm also getting this error

**Comment by rymesaint** [comment]
i've found the solution changing the youtube client using YoutubeApiClient.androidVr or YoutubeApiClient.android is working

**Comment by shrutgyan** [comment]
> i've found the solution changing the youtube client using YoutubeApiClient.androidVr or YoutubeApiClient.android is working

Where do we change this??

**Comment by jelle-limpens** [comment]
> > i've found the solution changing the youtube client using YoutubeApiClient.androidVr or YoutubeApiClient.android is working
> 
> Where do we change this??

You can select which client to use when calling the stream.

**Comment by tihomir-kit** [comment]
In my case, this helped:

https://github.com/newtaDev/pod_player/issues/238#issuecomment-2698679766

Essentially in pubspec:

```
# temporary fix
dependency_overrides:
  youtube_explode_dart: 2.3.0
```
