### ISSUE TITLE
 Error: The getter 'qualityLabel' isn't defined for the class 'Muxed

### ISSUE THREAD

**Issue by user97116** [newtaDev/pod_player#24]
: Error: The getter 'qualityLabel' isn't defined for the class 'MuxedStreamInfo'.
../…/controllers/pod_video_quality_controller.dart:101
- 'MuxedStreamInfo' is from 'package:youtube_explode_dart/src/videos/streams/muxed_stream_info.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/youtube_explode_dart-1.9.10/lib/src/videos/streams/muxed_stream_info.dart').
package:youtube_explode_dart/…/streams/muxed_stream_info.dart:1
Try correcting the name to the name of an existing getter, or defining a getter or field named 'qualityLabel'.

              quality: int.parse(element.qualityLabel.split('p')[0]),
                                         ^^^^^^^^^^^^

**Comment by newtaDev** [comment]
If You are using `youtube_explode_dart` package then  please upgrade it to the latest version 
or 
delete `pubspec.lock` and run `flutter pub get`

**Comment by user97116** [comment]
@newtaDev I used only pod player

**Comment by newtaDev** [comment]
> @newtaDev I used only pod player I tried delete .pub cache clean project, but still it's same error

delete `pubspec.lock` file from your project folder and run `flutter pub get` .
This should work
