### ISSUE TITLE
Exception: videoQuality cannot be empty

### ISSUE THREAD

**Issue by aibekdv** [newtaDev/pod_player#247]
When playing videos in the app, some videos work as expected, while others cause the app to crash with the following error:
`E/flutter ( 3806): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: videoQuality cannot be empty`

**Comment by sarvarofficial** [comment]
> When playing videos in the app, some videos work as expected, while others cause the app to crash with the following error: `E/flutter ( 3806): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: videoQuality cannot be empty`

last_pod_player: ^0.0.5  use it
