### ISSUE TITLE
Overlay doesn't cover full player when PodVideoPlayer has padding around

### ISSUE THREAD

**Issue by Cosminnv** [newtaDev/pod_player#27]
As title says, overlay is smaller than the video player when there's padding. 
![1654073213424](https://user-images.githubusercontent.com/48117967/171365449-81c5bdb4-b98e-4a49-9730-8016383179db.JPEG)
![1654073207146](https://user-images.githubusercontent.com/48117967/171365459-e5f046af-0197-45f6-8b0b-b5957a6ea255.JPEG)

To replicate :
Use the sample app, play a video from a vimeo id (this is the only one I tried but I think it happens on all of them) and add padding around PodVideoPlayer:

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Vimeo Player')),
      body: SafeArea(
        child: Center(
          child: ListView(
            shrinkWrap: true,
            children: [
              Padding(
                padding: const EdgeInsets.all(35),
                child: PodVideoPlayer(
                  controller: controller,
                  alwaysShowProgressBar: false,
                ),
              ),
            ],
          ),
        ),
      ),
    );
}`

**Comment by newtaDev** [comment]
> Update: seems to be an aspect ratio problem, if you play around with "frameAspectRatio" you can make it match the player. In my case I set it to 16/8.8. "matchVideoAspectRatioToFrame" set to true doesn't seem to work either

Thanks for the update 🤗
Yeah, use Aspect ratio if possible instead of wrapping it with padding or other constraints widgets.

This `matchVideoAspectRatioToFrame` Initially takes the aspect ratio from the video's metadata and matches it with the frame
