### ISSUE TITLE
Can you replace getx with riverpod or provider

### ISSUE THREAD

**Issue by prateekmedia** [newtaDev/pod_player#28]
Getx is bloat and I don't think you are using all the functionalities of getx for this. Although it comes to personal choice but still I would prefer a river pod/ providers version of this instead of getx.

**Comment by newtaDev** [comment]
> Getx is bloat and I don't think you are using all the functionalities of getx for this. Although it comes to personal choice but still I would prefer a river pod/ providers version of this instead of getx.

Yeah, I was planning to migrate to `riverpod` or `flutter_bloc`
But for me as of now, it takes a lot of time and effort  🥲

please let me know if u are willing to help me with this 🤗
