### ISSUE TITLE
Playing video in list

### ISSUE THREAD

**Issue by qbait** [newtaDev/pod_player#32]
Hi, thank you for developing that awesome package!

Currently, I'm using it to show videos in list. I would like to achieve the similar effect like Facebook or Twitter does (when scrolling the videos are automatically played).

To play with that, I've edited `from_youtube.dart` from your sample app, the code below.
```
import 'package:flutter/material.dart';
import 'package:pod_player/pod_player.dart';
import 'package:visibility_detector/visibility_detector.dart';

class PlayVideoFromYoutube extends StatefulWidget {
  const PlayVideoFromYoutube({Key? key}) : super(key: key);

  @override
  State<PlayVideoFromYoutube> createState() => _PlayVideoFromVimeoIdState();
}

class _PlayVideoFromVimeoIdState extends State<PlayVideoFromYoutube> {
  final videos = [
    'https://youtu.be/A3ltMaM6noM',
    'https://www.youtube.com/watch?v=TjBA6jy4ako',
    'https://www.youtube.com/watch?v=HqFgRHTuDyc',
  ];

  late final PodPlayerController controller;
  final videoTextFieldCtr = TextEditingController();

  @override
  void initState() {
    controller = PodPlayerController(
      playVideoFrom: PlayVideoFrom.youtube(videos[0]),
      podPlayerConfig: const PodPlayerConfig(autoPlay: true),
    );

    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Youtube player')),
      body: SafeArea(
        child: ListView(
          children: [
            const SizedBox(height: 200),
            _videoPlayer(videos[0]),
            const SizedBox(height: 900),
            _videoPlayer(videos[1]),
            const SizedBox(height: 900),
            _videoPlayer(videos[2]),
            const SizedBox(height: 200),
          ],
        ),
      ),
    );
  }

  Widget _videoPlayer(String videoUrl) {
    return VisibilityDetector(
      key: Key(videoUrl),
      onVisibilityChanged: (VisibilityInfo info) {
        if (info.visibleFraction == 1) {
          if (controller.isVideoPlaying) return;

          controller.changeVideo(
            playVideoFrom: PlayVideoFrom.youtube(videoUrl),
            playerConfig: const PodPlayerConfig(autoPlay: true),
          );
        } else {
          controller.pause();
        }
      },
      child: PodVideoPlayer(
          controller: controller,
      ),
    );
  }
}
```

1. However, there is an issue that videos aren't played automatically after `changeVideo` even if I'm explicitely calling `autoplay: true`
```
          controller.changeVideo(
            playVideoFrom: PlayVideoFrom.youtube(videoUrl),
            playerConfig: const PodPlayerConfig(autoPlay: true),
          );
```
https://user-images.githubusercontent.com/2264901/175293409-221d70a4-c7b8-44fc-9aaa-4ae3dfaf0b67.mp4

2. Also, as you can see the video isn't loaded immediately so I wanted to show thumbnails when the video is loading. 
so I've added `videoThumbnail` to `PodVideoPlayer`
```
      child: PodVideoPlayer(
        controller: controller,
        videoThumbnail: DecorationImage(
          image: NetworkImage(_thumbnailUrl(videoUrl)),
        ),
      ),
```
However, it doesn't seem to work correctly as well
https://user-images.githubusercontent.com/2264901/175294717-54325703-bcd8-4178-be82-bb905f0eca49.mp4

**Comment by qbait** [comment]
Thank you for the answer @newtaDev.
However, in my case, I need to handle pagination, and I don't know all videos at the start.
That's why I'm playing with the above sample with dynamic reloading.

**Comment by newtaDev** [comment]
I have created a new example file for playing videos in list 
https://github.com/newtaDev/pod_player/blob/fix/videos_list/example/lib/examples/play_videos_list_dynamically.dart

change dependency to use this example in pubspec.yml
if everything works then I will upload to pub.dev 

```
  pod_player:
    git:
      url: git@github.com:newtaDev/pod_player.git
      ref: fix/videos_list
```

**Comment by qbait** [comment]
@newtaDev unfortunately, the problem still exists.

Let's say you add 50 videos. My Pixel 2 in that case, will throw `OutOfMemoryException`

https://user-images.githubusercontent.com/2264901/176128648-b512dec8-5979-4b5d-b862-29af7d1258b4.mp4

**Comment by newtaDev** [comment]
Show your error log.. 
Please test in physical devices instead of emulator

**Comment by newtaDev** [comment]
In production application we never load all videos simultaneously.. 
Use pagination instead 😉

**Comment by Vladilisan** [comment]
For me it doesn't work to access the git. Flutter throws this error "Please make sure you have the correct access rights
and the repository exists.
exit code: 128"

I think I am going to wait until you launch to pub.dev. Please let us know when that will happen. Thank you very much ;)

**Comment by newtaDev** [comment]
@Vladilisan 
To use git repo you need to configure ssh key for git

**Comment by jigarfumakiya** [comment]
Did anyone find a solution here?
