### ISSUE TITLE
Additional video controls

### ISSUE THREAD

**Issue by qbait** [newtaDev/pod_player#33]
Would it be possible to add controls like:
- Mute
- YouTube button (redirecting to YT)

like on the following image?
<img width="711" alt="Screenshot 2022-06-23 at 16 51 09" src="https://user-images.githubusercontent.com/2264901/175334772-817d2741-da45-4e6c-996d-28cb0e2e06da.png">

**Comment by newtaDev** [comment]
You can use `overlayBuilder` for fully customizing video overlay
 
Try this simple example:

```dart
PodVideoPlayer(
    controller: controller,
    alwaysShowProgressBar: false,
    overlayBuilder: (options) {
      return Container(
        color: Colors.grey.withOpacity(0.2),
        child: Center(
          child: Column(
            children: [
              ElevatedButton(
                child: Text(
                  options.isMute ? 'UnMute' : 'Mute',
                ),
                onPressed: () {
                  controller.toggleVolume();
                  setState(() {});
                },
              )
            ],
          ),
        ),
      );
    }),
```

**Comment by newtaDev** [comment]
Im closing this issue,
If u face any issues in `overlayBuilder` then please reopen it🤗
