### ISSUE TITLE
Video list auto-pause.

### ISSUE THREAD

**Issue by Vladilisan** [newtaDev/pod_player#34]
Hi, awesome package. 
The problem I am facing is that when I press play on a video while another one is playing, the previous video doesn't pause. It stops playing but the state remains as playing which causes a few issues.

I'm curious why this hasn't been discussed yet, maybe I am doing something wrong but I am out of ideas.

Thank you ;)

**Comment by newtaDev** [comment]
Hai, Thank you for opening the issue 🤗
Can you please share the steps to reproduce the issue?

**Comment by Vladilisan** [comment]
Thank you for your reply.
Here is an example I put together.

`class VideoList extends StatefulWidget {
  @override
  State<AnswerPage> createState() => _VideoList();
}

class _VideoList extends State<AnswerPage> {
  late final PodPlayerController controller1;
  late final PodPlayerController controller2;

  @override
  void initState() {
    controller1 = PodPlayerController(
        playVideoFrom: PlayVideoFrom.vimeo('70591644'),
        podPlayerConfig: PodPlayerConfig(
            autoPlay: false, isLooping: false, initialVideoQuality: 360))
      ..initialise();

    controller2 = PodPlayerController(
        playVideoFrom: PlayVideoFrom.vimeo('70591644'),
        podPlayerConfig: PodPlayerConfig(
            autoPlay: false, isLooping: false, initialVideoQuality: 360))
      ..initialise();
    super.initState();
  }

  @override
  void dispose() {
    controller1.dispose();
    controller2.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Column(
              children: [
                PodVideoPlayer(controller: controller1),
                PodVideoPlayer(controller: controller2),
              ],
            ),
          ),
        ));
  }
}
`

**Comment by qbait** [comment]
I have created issue as well https://github.com/newtaDev/pod_player/issues/32
Would be great to have a sample and see your vision regarding the list that is dynamically recycling video controllers and pausing / resuming when  scrolling.

**Comment by qbait** [comment]
Without dynamic management there is gonna be `OutOfMemoryError` for more videos

```
W/example.exampl( 9496): Throwing OutOfMemoryError "Failed to allocate a 32 byte allocation with 0 free bytes and 0B until OOM, target footprint 201551904, growth limit 201326592" (VmSize 21179068 kB, recursive case)
I/example.exampl( 9496): Waiting for a blocking GC Alloc
I/example.exampl( 9496): Waiting for a blocking GC Alloc
W/example.exampl( 9496): "ExoPlayer:Loader:ProgressiveMediaPeriod" prio=5 tid=117 Runnable
W/example.exampl( 9496):   | group="main" sCount=0 dsCount=0 flags=0 obj=0x12c4a4f0 self=0x77c6b982c0
W/example.exampl( 9496):   | sysTid=20788 nice=0 cgrp=default sched=0/0 handle=0x7535afccc0
W/example.exampl( 9496):   | state=R schedstat=( 454941363 46143957 516 ) utm=40 stm=4 core=5 HZ=100
W/example.exampl( 9496):   | stack=0x75359f9000-0x75359fb000 stackSize=1043KB
W/example.exampl( 9496):   | held mutexes= "mutator lock"(shared held)
W/example.exampl( 9496):   at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.seekMap(ProgressiveMediaPeriod.java:694)
W/example.exampl( 9496):   at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:557)
W/example.exampl( 9496):   at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:453)
W/example.exampl( 9496):   at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:435)
W/example.exampl( 9496):   at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:253)
W/example.exampl( 9496):   at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
W/example.exampl( 9496):   at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
W/example.exampl( 9496):   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
W/example.exampl( 9496):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/example.exampl( 9496):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/example.exampl( 9496):   at java.lang.Thread.run(Thread.java:923)
W/example.exampl( 9496): "ExoPlayer:Loader:ProgressiveMediaPeriod" prio=5 tid=117 Runnable
W/example.exampl( 9496):   | group="main" sCount=0 dsCount=0 flags=0 obj=0x12c4a4f0 self=0x77c6b982c0
W/example.exampl( 9496):   | sysTid=20788 nice=0 cgrp=default sched=0/0 handle=0x7535afccc0
W/example.exampl( 9496):   | state=R schedstat=( 454941363 46143957 516 ) utm=40 stm=4 core=5 HZ=100
W/example.exampl( 9496):   | stack=0x75359f9000-0x75359fb000 stackSize=1043KB
W/example.exampl( 9496):   | held mutexes= "mutator lock"(shared held)
```

**Comment by newtaDev** [comment]
This issue seems similar to #32 so I'm closing this issue
please continue the discussion in #32
