### ISSUE TITLE
[Feature Request] Full Screen By Default

### ISSUE THREAD

**Issue by adharmi** [newtaDev/pod_player#36]
Hello,
Firstly, Thanks to the developers and contributors of this awesome Video-Player package.

I want to request for a simple feature,
For now i see there are only these options in PodPlayerConfig
> bool autoPlay = true
> bool isLooping = false
> bool forcedVideoFocus = false
> bool wakelockEnabled = true
> int? initialVideoQuality

Can the developer or anyone add one more option/ feature
> bool fullScreenByDefault = false

And this should allow the package users to select the default player mode, either fullscreen or the minimized window (which is default for now on android & ios)

And if someone is going to work on it, please add two more options -
> bool allowFullScreen = true

To show and hide the Full-Screen button on player, allowing the package users to enable/ disable Full-Screen mode for its users.

> bool showOptionsMenu

To show and hide the Top-Right Three Dots Menu button on player.

**Comment by newtaDev** [comment]
> And this should allow the package users to select the default player mode, either fullscreen or the minimized window (which is default for now on android & ios)

your can use `enableFullScreen` function in initstate
```dart
  @override
  void initState() {
    controller = PodPlayerController(
      playVideoFrom: PlayVideoFrom.asset('assets/SampleVideo_720x480_20mb.mp4'),
    )..initialise().then((_) => controller.enableFullScreen());
    super.initState();
  }
```


> bool allowFullScreen = true
To show and hide the Full-Screen button on player, allowing the package users to enable/ disable Full-Screen mode for its users.

For customizing overlay widget ref https://github.com/newtaDev/pod_player/issues/33#issuecomment-1164748196
