### ISSUE TITLE
Add pip mode support

### ISSUE THREAD

**Issue by prateekmedia** [newtaDev/pod_player#39]
Youtube player in premium mode has this functionality, It goes to pip mode when minimized.

So is it possible to be implemented in pod player?

**Comment by newtaDev** [comment]
I'm not sure how to implement pip mode, need to figure it out.
If anyone is familiar with pip mode then please help. This will be a great feature to have on pod_player

**Comment by prateekmedia** [comment]
I think the pip feature should be part of the app itself as we have to handle it separately as also done by SongTube, so closing the issue
https://github.com/SongTube/SongTube-App/blob/caa8f28bfeddc95b4c1da67e3436c8dd51e2457e/pubspec.yaml#L112
