### ISSUE TITLE
If we change video from youtube player to network player without dynamic quality, the quality option doesn't hide away and upon clicking the quality previous video is played.

### ISSUE THREAD

**Issue by B33pin** [newtaDev/pod_player#4]

**Comment by newtaDev** [comment]
Please provide reproducible code and some screenshots for reference

**Comment by newtaDev** [comment]
Thanks for opening the issue,
let me look into it.

**Comment by B33pin** [comment]
> Thanks for opening the issue, let me look into it.

Yes please, try to fix as soon as possible. BTW love your package.
