### ISSUE TITLE
No option to hide custom overlay if the video is playing.

### ISSUE THREAD

**Issue by yoannpicquenot** [newtaDev/pod_player#47]
Hi,

I was looking for an option to allow my custom overlay made with the overlayBuilder but never found it.
Either I'm not looking in the right place or it does not exist. So do tell me if exists 🙂

From what I could see:

lib/src/widgets/core/overlays/overlays.dart, line 37:

```
Stack(
  children: [
    Positioned.fill(
      child: _VideoGestureDetector(
        tag: tag,
        onTap: _podCtr.togglePlayPauseVideo,
        onDoubleTap: () =>
            _podCtr.toggleFullScreenOnWeb(context, tag),
        child: const ColoredBox(
          color: Colors.black38,
          child: SizedBox.expand(),
        ),
      ),
    ),
    _podCtr.overlayBuilder?.call(overlayOptions) ?? const SizedBox(),
  ],
);
```

That ColoredBox has no condition in order to be hidden or to get removed.
If an option is not necessary, I would suggest to hide the ColoredBox when `!_podCtrl.isOverlayVisible`.

Regards.

**Comment by emersonsiega** [comment]
I had an issue with this ColoredBox too... 
I've changed this behavior in my fork and will send a PR with this improvement as soon as possible :)
