### ISSUE TITLE
onFullScreenToggle callback

### ISSUE THREAD

**Issue by xurc** [newtaDev/pod_player#48]
Is there any way to restore the app's PreferredOrientations after exiting fullScreen mode?

The application sets the preferred orientation at startup, but after switching the video to fullscreen and back (even when autoplay to false, just after switching to fullscreen preview), the application starts responding to a change in device orientation.

I did not find anything suitable in the API.

For example, it could be like this:
```dart
    controller.onFullScreenOff(() => SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]));
```

**Comment by emersonsiega** [comment]
I'm having this same problem and other, also related to full screen mode. 

I have to allow users to open video in full screen mode but keep the device in portraitUp orientation. Something like this:  

<img width="302" alt="image" src="https://user-images.githubusercontent.com/2227499/180904186-a2777f0d-cd74-45b1-99d5-4dd42d9a2b40.png">

If user turns the device to landscape mode, then, the player have to rotate automatically.

There's the possibility to provide callbacks to override the `setPreferredOrientations` options? It would help me a lot! 

@newtaDev can you take a look here? Thank you!

**Comment by xurc** [comment]
> I have to allow users to open video in full screen mode but keep the device in portraitUp orientation.

To do this, you can wrap the video preview in `GestureDetector` and open the player simply on a separate page through the `Navigator.push`. In this case, everything will be like in your screenshot, the user will have the opportunity to go to fullscreen using the built-in player button, and the orientation can be restored on pressing "back" before `Navigator.pop`.

This is how we did it and it works, but now we want to play the video inline, and in this case we need either callbacks or parameters for` PreferredOrientations` so that it is restored inside the player.

**Comment by emersonsiega** [comment]
I have created these callbacks in my fork... I'm making other changes right now, but as soon as possible I'll send a PR.
