### ISSUE TITLE
Error while playing video. 

### ISSUE THREAD

**Issue by ps6067966** [newtaDev/pod_player#5]
while playing Youtube video i getting this error.

**Comment by newtaDev** [comment]
Can u please mention what's the error

**Comment by aorohith** [comment]
Can i play video from asset, There is an error showing in my app like, "Error while playing the video".
 playVideoFrom: PlayVideoFrom.asset(
        'assets/videos/ForBiggerFun.mp4',
      ),
The above was the code, Please help me with a solution

**Comment by newtaDev** [comment]
check your video file path
