### ISSUE TITLE
Additional border on Android device

### ISSUE THREAD

**Issue by emersonsiega** [newtaDev/pod_player#53]
I'm facing a problem with an Android device (Samsung Galaxy A10 - Android 11), where a strange border is added to the VideoPlayer...

To reproduce, just add a Padding to the example project...
![image](https://user-images.githubusercontent.com/2227499/181803046-a5a7a046-3b16-4a62-a9a3-b4fd0a609895.png)

While is loading, this not happens...
![image](https://user-images.githubusercontent.com/2227499/181803431-4141f16b-32b7-45df-b372-0c69a8194a70.png)

This border not appears on iOS (iPhone 7):
<img width="376" alt="image" src="https://user-images.githubusercontent.com/2227499/181803796-d9804d08-5efa-4e61-87a5-6d61318aef1e.png">

**Comment by emersonsiega** [comment]
@newtaDev can you help me with this issue?
I was debugging but couldn't find what's happening...

**Comment by emersonsiega** [comment]
I don't know why, but it doesn't happening anymore 🤷🏻‍♂️, so I'll close this issue

**Comment by newtaDev** [comment]
While testing this issue, I was unable to reproduce it.
I'm not sure why it happened.

Thanks for closing ✌️
