### ISSUE TITLE
Launch in full screen mode

### ISSUE THREAD

**Issue by Minsamin** [newtaDev/pod_player#57]
Is there any possibility to launch the player directly in full screen mode ?

Tried "`controller.enableFullScreen();`" in `initState` And in `Build` method.
Its giving "`mainContext`" not initialised 

This is the issue 
in `_PodBaseController` =>  `late BuildContext mainContext;`

**Comment by newtaDev** [comment]
Thank you for filling issue 🤗

To Support FulllScreen Initially 
In `Pod player <= 0.0.8`
```dart
@override
  void initState() {
    controller = PodPlayerController(
      playVideoFrom: PlayVideoFrom.network(
        'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
      ),
    )..initialise().then((_) => controller.enableFullScreen());
    super.initState();
  }
```

In `Pod player >= 0.1.0`
```dart
@override
  void initState() {
    controller = PodPlayerController(
      playVideoFrom: PlayVideoFrom.network(
        'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
      ),
    )
      ..initialise()
      ..enableFullScreen();
    super.initState();
  }
```

**Comment by newtaDev** [comment]
I hope this https://github.com/newtaDev/pod_player/issues/57#issuecomment-1204787817 fixed your issues
Im closing this issue, Please feel free to reopen if still any issues exists
