### ISSUE TITLE
long load time 

### ISSUE THREAD

**Issue by mohammedebrahim1** [newtaDev/pod_player#9]
for videos that over 40 minutes have very long time to star video also if change quality start to load again it takes 15 to 20 seconds

**Comment by newtaDev** [comment]
On which YouTube or network or Vimeo?

**Comment by mohammedebrahim1** [comment]
YouTube

**Comment by newtaDev** [comment]
I think this package has nothing to do with the long loading time of youtube/Vimeo videos.
it mostly depends on the network speed and latency of the server.

**Comment by mohammedebrahim1** [comment]
try https://pub.dev/packages/youtube_player_flutter doesn't have long time to init video

**Comment by newtaDev** [comment]
Now this issue is being reported frequently
Let me see if I can find any workaround for this problem

**Comment by newtaDev** [comment]
I have separated Api calling and video loading functions for youtube and Vimeo. 
So that u can call specific Api's initially to reduce the loading time of the video.
> **Note**
> These API always returns `List<VideoQalityUrls>?` 

> API for Calling the Youtube video 
```dart
final _urls = await PodPlayerController.getYoutubeUrls( 'https://youtu.be/A3ltMaM6noM' );
```
> API for Calling the Vimeo video 
```dart
final _urls = await PodPlayerController.getVimeoUrls('518228118');
```
> Pass `_urls` to `PlayVideoFrom.networkQualityUrls`

```dart 
controller = PodPlayerController(
      playVideoFrom: PlayVideoFrom.networkQualityUrls(videoUrls: _urls!),
      podPlayerConfig: const PodPlayerConfig(
        initialVideoQuality: 360,
      ),
    )..initialise();
```

[Full Example](https://github.com/newtaDev/pod_player/blob/master/example/lib/examples/load_youtubes_from_urls.dart)
