### ISSUE TITLE
YOUTUBE API ERROR: XMLHttpRequest error. (Playing in Web)

### ISSUE THREAD

**Issue by Priyank248** [newtaDev/pod_player#98]
YOUTUBE API ERROR: XMLHttpRequest error.
VIMEO API ERROR: XMLHttpRequest error.

=> I got this error while playing youtube and vimeo video url in pod_player.
=> I'm using same URL & ID as you mentioned here -> https://pub.dev/packages/pod_player
=> please, help to solve this error. @newtaDev

**Comment by newtaDev** [comment]
There are some limitations in web:
So u need to enable CORS 
Ref: #15 
https://github.com/newtaDev/pod_player#web--not-recommended-in-production

Duplicate: #15
